name: Advanced Usage

on: push

jobs:
  convert_via_pandoc:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - name: create file list
        run: |
          mkdir output

      - uses: docker://pandoc/latex:2.9
        with:
          args: --output=output/Jour1.pdf Jour1.md
      - uses: docker://pandoc/latex:2.9
        with:
          args: --output=output/Jour2.pdf Jour2.md
      - uses: docker://pandoc/latex:2.9
        with:
          args: --output=output/Jour3.pdf Jour3.md

      - uses: actions/upload-artifact@v3
        with:
          name: output
          path: output